apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stateless-app
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: stateless-app
        tier: dev
    spec:
      containers:
        - name: stateless-app
          image: stateless-app #FIXME
        - image: nginx:1.15
          name: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: conf
      volumes:
      - name: conf
        configMap:
          name: nginx