apiVersion: v1
kind: Service
metadata:
  name: stateless-app-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: stateless-app
spec:
  type: LoadBalancer
  selector:
    app: stateless-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP