apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stateless-app
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: stateless-app
        app: stateless-app
    spec:
      containers:
        - name: stateless-app
          image: richardps/articles-api:latest
          
        - image: nginx:1.15
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: conf
      volumes:
      - name: conf
        configMap:
          name: nginx